[package]
name = "climer"
version = "0.0.1"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
description = "CLI timer app"

[dependencies]
regex = "1.1.0"
clap = "2.32.0"
climer_derive = { path = "./climer_derive" }

[[bin]]
name = "climer"
path = "src/main.rs"
